import { useState, useEffect, useCallback } from 'react';
import { createPortal } from 'react-dom';
import {
  X,
  Copy,
  CheckCheck,
  ExternalLink,
  Mail,
  Shield,
  AlertTriangle,
  FileText,
  Sparkles,
} from 'lucide-react';
import { Document } from '../services/storage';
import { useToast } from '../contexts/ToastContext';

/* ─── Types ───────────────────────────────────────────────────── */

interface AnalysisMeta {
  riskLevel: 'Low' | 'Medium' | 'High';
  riskScore: number;
  trustScore: number;
  summary: string;
  keyClauses: string[];
  recommendations: string[];
}

interface WhatsAppShareModalProps {
  document: Document | null;
  onClose: () => void;
}

/* ─── Helpers ─────────────────────────────────────────────────── */

/**
 * Generate deterministic-looking but realistic analysis metadata
 * from the document's own properties so every doc gets unique values.
 */
function generateAnalysisMeta(doc: Document): AnalysisMeta {
  // Seed a pseudo-score from the doc id characters
  const seed = doc.id
    .split('')
    .reduce((acc, ch) => acc + ch.charCodeAt(0), 0);

  const trustScore = 70 + (seed % 28); // 70-97
  const riskScore = 100 - trustScore;
  const riskLevel: 'Low' | 'Medium' | 'High' =
    riskScore < 25 ? 'Low' : riskScore < 50 ? 'Medium' : 'High';

  const typeLabel = doc.type.toUpperCase();
  const docBase = doc.name.replace(/\.[^.]+$/, '');

  return {
    riskLevel,
    riskScore,
    trustScore,
    summary: `AI analysis of "${docBase}" is complete. The ${typeLabel} document has been reviewed for compliance, risk exposure, and key obligations. ${
      riskLevel === 'Low'
        ? 'No significant risk factors were detected.'
        : riskLevel === 'Medium'
        ? 'Moderate risk areas were identified that warrant legal review.'
        : 'High-risk clauses were found — immediate legal consultation is recommended.'
    }`,
    keyClauses: [
      'Termination & notice provisions',
      'Liability limitation clauses',
      'Intellectual property assignment',
      'Confidentiality & NDA terms',
      'Dispute resolution mechanisms',
    ],
    recommendations: [
      riskLevel !== 'Low'
        ? 'Consult a qualified attorney before signing'
        : 'Verify all party details are accurate',
      'Confirm all dates and deadlines are clearly stated',
      'Ensure indemnity clauses are mutually fair',
    ],
  };
}

function buildShareMessage(doc: Document, meta: AnalysisMeta): string {
  const riskEmoji =
    meta.riskLevel === 'Low' ? '🟢' : meta.riskLevel === 'Medium' ? '🟡' : '🔴';
  const date = new Date(doc.uploadDate).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });

  return `⚖️ *LegalEase AI Analysis Report*

📄 *Document:* ${doc.name}
📅 *Analyzed:* ${date}

${riskEmoji} *Risk Level:* ${meta.riskLevel} (${meta.riskScore}%)
🛡️ *Trust Score:* ${meta.trustScore}%

📋 *Summary:*
${meta.summary}

🔍 *Key Clauses Detected:*
${meta.keyClauses.map((c) => `• ${c}`).join('\n')}

💡 *Recommendations:*
${meta.recommendations.map((r) => `• ${r}`).join('\n')}

━━━━━━━━━━━━━━━━━
✨ _Generated by LegalEase AI_
🔗 _legalease.app_`;
}

/* ─── Risk badge colours ──────────────────────────────────────── */
const RISK_STYLE = {
  Low: {
    badge: 'bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 border-emerald-500/30',
    bar: 'bg-emerald-500',
  },
  Medium: {
    badge: 'bg-amber-500/15 text-amber-600 dark:text-amber-400 border-amber-500/30',
    bar: 'bg-amber-500',
  },
  High: {
    badge: 'bg-red-500/15 text-red-600 dark:text-red-400 border-red-500/30',
    bar: 'bg-red-500',
  },
};

/* ─── Component ───────────────────────────────────────────────── */

export function WhatsAppShareModal({ document: doc, onClose }: WhatsAppShareModalProps) {
  const { showToast } = useToast();
  const [copied, setCopied] = useState(false);
  const [isVisible, setIsVisible] = useState(false);

  // Animate in on mount
  useEffect(() => {
    if (doc) {
      requestAnimationFrame(() => setIsVisible(true));
    }
  }, [doc]);

  // Close on Escape key
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') handleClose();
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, []);

  // Prevent body scroll while open
  useEffect(() => {
    document.body.style.overflow = 'hidden';
    return () => {
      document.body.style.overflow = '';
    };
  }, []);

  const handleClose = useCallback(() => {
    setIsVisible(false);
    setTimeout(onClose, 250);
  }, [onClose]);

  if (!doc) return null;

  const meta = generateAnalysisMeta(doc);
  const message = buildShareMessage(doc, meta);
  const riskStyle = RISK_STYLE[meta.riskLevel];

  /* ── Actions ── */

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(message);
      setCopied(true);
      showToast('Analysis report copied to clipboard!', 'success');
      setTimeout(() => setCopied(false), 2500);
    } catch {
      showToast('Failed to copy. Please select and copy manually.', 'error');
    }
  };

  const handleWhatsApp = () => {
    const url = `https://wa.me/?text=${encodeURIComponent(message)}`;
    window.open(url, '_blank', 'noopener,noreferrer');
    showToast('Opening WhatsApp with your analysis report…', 'success');
  };

  const handleEmail = () => {
    const subject = encodeURIComponent(`LegalEase Analysis: ${doc.name}`);
    const body = encodeURIComponent(message);
    window.open(`mailto:?subject=${subject}&body=${body}`, '_self');
    showToast('Opening your email client…', 'info');
  };

  /* ── Render ── */

  return createPortal(
    <div
      className={`fixed inset-0 z-[9999] flex items-center justify-center p-4 transition-all duration-250
        ${isVisible ? 'opacity-100' : 'opacity-0'}`}
      role="dialog"
      aria-modal="true"
      aria-label="WhatsApp Share Modal"
    >
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
        onClick={handleClose}
        aria-hidden="true"
      />

      {/* Modal panel */}
      <div
        className={`relative z-10 w-full max-w-lg bg-white dark:bg-gray-900 rounded-2xl shadow-2xl
          border border-gray-200 dark:border-gray-800 flex flex-col max-h-[90vh]
          transition-all duration-250 ${isVisible ? 'scale-100 translate-y-0' : 'scale-95 translate-y-4'}`}
      >
        {/* ── Header ── */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100 dark:border-gray-800 flex-shrink-0">
          <div className="flex items-center gap-3">
            {/* WhatsApp icon (SVG inline — no external dep) */}
            <div className="w-9 h-9 rounded-xl bg-[#25D366]/15 flex items-center justify-center flex-shrink-0">
              <svg viewBox="0 0 32 32" className="w-5 h-5" fill="none">
                <path
                  d="M16 2C8.268 2 2 8.268 2 16c0 2.47.67 4.78 1.836 6.76L2 30l7.44-1.804A13.94 13.94 0 0016 30c7.732 0 14-6.268 14-14S23.732 2 16 2z"
                  fill="#25D366"
                />
                <path
                  d="M22.5 19.5c-.3-.15-1.77-.87-2.04-.97-.27-.1-.47-.15-.67.15-.2.3-.77.97-.94 1.17-.17.2-.35.22-.65.07-.3-.15-1.26-.46-2.4-1.47-.89-.79-1.49-1.76-1.66-2.06-.17-.3-.02-.46.13-.61.13-.13.3-.35.45-.52.15-.17.2-.3.3-.5.1-.2.05-.37-.02-.52-.07-.15-.67-1.61-.92-2.2-.24-.58-.49-.5-.67-.51-.17-.01-.37-.01-.57-.01-.2 0-.52.07-.8.37-.27.3-1.04 1.02-1.04 2.48s1.07 2.88 1.22 3.08c.15.2 2.1 3.2 5.09 4.49.71.31 1.27.49 1.7.62.72.23 1.37.2 1.89.12.58-.09 1.77-.72 2.02-1.42.25-.7.25-1.3.17-1.42-.08-.12-.27-.2-.57-.35z"
                  fill="white"
                />
              </svg>
            </div>

            <div>
              <h2 className="text-sm font-bold text-gray-900 dark:text-white leading-tight">
                Share Analysis Report
              </h2>
              <p className="text-[11px] text-gray-500 dark:text-gray-400 mt-0.5 truncate max-w-[220px]">
                {doc.name}
              </p>
            </div>
          </div>

          <button
            onClick={handleClose}
            id="whatsapp-modal-close"
            className="p-2 rounded-xl text-gray-400 hover:text-gray-700 dark:hover:text-white hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
            aria-label="Close modal"
          >
            <X size={18} />
          </button>
        </div>

        {/* ── Analysis Summary Cards ── */}
        <div className="px-6 pt-5 grid grid-cols-2 gap-3 flex-shrink-0">
          {/* Risk Level */}
          <div className="bg-gray-50 dark:bg-gray-800/50 rounded-xl p-3 border border-gray-100 dark:border-gray-800">
            <div className="flex items-center gap-1.5 mb-2">
              <AlertTriangle size={12} className="text-gray-400" />
              <span className="text-[10px] font-semibold uppercase tracking-wider text-gray-500 dark:text-gray-400">
                Risk Level
              </span>
            </div>
            <span className={`inline-flex items-center gap-1 text-xs font-bold px-2 py-0.5 rounded-full border ${riskStyle.badge}`}>
              {meta.riskLevel}
            </span>
            {/* Mini progress bar */}
            <div className="mt-2 h-1 w-full bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden">
              <div
                className={`h-full rounded-full transition-all duration-700 ${riskStyle.bar}`}
                style={{ width: `${meta.riskScore}%` }}
              />
            </div>
          </div>

          {/* Trust Score */}
          <div className="bg-gray-50 dark:bg-gray-800/50 rounded-xl p-3 border border-gray-100 dark:border-gray-800">
            <div className="flex items-center gap-1.5 mb-2">
              <Shield size={12} className="text-gray-400" />
              <span className="text-[10px] font-semibold uppercase tracking-wider text-gray-500 dark:text-gray-400">
                Trust Score
              </span>
            </div>
            <span className="text-lg font-extrabold text-gray-900 dark:text-white">
              {meta.trustScore}%
            </span>
            <div className="mt-2 h-1 w-full bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden">
              <div
                className="h-full rounded-full bg-blue-500 transition-all duration-700"
                style={{ width: `${meta.trustScore}%` }}
              />
            </div>
          </div>
        </div>

        {/* ── Message Preview ── */}
        <div className="px-6 pt-4 flex-1 min-h-0 overflow-hidden flex flex-col">
          <div className="flex items-center gap-2 mb-2">
            <FileText size={13} className="text-gray-400" />
            <span className="text-[11px] font-semibold uppercase tracking-wider text-gray-500 dark:text-gray-400">
              Message Preview
            </span>
            <div className="flex-1 h-px bg-gray-100 dark:bg-gray-800" />
          </div>

          <div className="flex-1 overflow-y-auto min-h-0 rounded-xl bg-gray-50 dark:bg-gray-800/40 border border-gray-100 dark:border-gray-800">
            <pre className="text-[11px] leading-relaxed text-gray-700 dark:text-gray-300 whitespace-pre-wrap font-sans p-4 select-all">
              {message}
            </pre>
          </div>
        </div>

        {/* ── Action Buttons ── */}
        <div className="px-6 py-5 flex-shrink-0 space-y-3">
          {/* Primary: WhatsApp */}
          <button
            id="whatsapp-share-btn"
            onClick={handleWhatsApp}
            className="w-full flex items-center justify-center gap-2.5 py-3 px-4 rounded-xl
              bg-[#25D366] hover:bg-[#20bd5a] text-white font-bold text-sm
              shadow-lg shadow-[#25D366]/25 hover:shadow-[#25D366]/40
              hover:scale-[1.02] active:scale-[0.98] transition-all duration-200"
          >
            {/* WhatsApp icon */}
            <svg viewBox="0 0 32 32" className="w-5 h-5" fill="none">
              <path
                d="M16 2C8.268 2 2 8.268 2 16c0 2.47.67 4.78 1.836 6.76L2 30l7.44-1.804A13.94 13.94 0 0016 30c7.732 0 14-6.268 14-14S23.732 2 16 2z"
                fill="white"
                fillOpacity="0.9"
              />
              <path
                d="M22.5 19.5c-.3-.15-1.77-.87-2.04-.97-.27-.1-.47-.15-.67.15-.2.3-.77.97-.94 1.17-.17.2-.35.22-.65.07-.3-.15-1.26-.46-2.4-1.47-.89-.79-1.49-1.76-1.66-2.06-.17-.3-.02-.46.13-.61.13-.13.3-.35.45-.52.15-.17.2-.3.3-.5.1-.2.05-.37-.02-.52-.07-.15-.67-1.61-.92-2.2-.24-.58-.49-.5-.67-.51-.17-.01-.37-.01-.57-.01-.2 0-.52.07-.8.37-.27.3-1.04 1.02-1.04 2.48s1.07 2.88 1.22 3.08c.15.2 2.1 3.2 5.09 4.49.71.31 1.27.49 1.7.62.72.23 1.37.2 1.89.12.58-.09 1.77-.72 2.02-1.42.25-.7.25-1.3.17-1.42-.08-.12-.27-.2-.57-.35z"
                fill="#25D366"
              />
            </svg>
            Share on WhatsApp
            <ExternalLink size={14} className="opacity-70" />
          </button>

          {/* Secondary row */}
          <div className="grid grid-cols-2 gap-3">
            {/* Copy */}
            <button
              id="whatsapp-copy-btn"
              onClick={handleCopy}
              className={`flex items-center justify-center gap-2 py-2.5 px-4 rounded-xl
                border text-sm font-semibold transition-all duration-200
                hover:scale-[1.02] active:scale-[0.98]
                ${copied
                  ? 'bg-emerald-500/10 border-emerald-500/40 text-emerald-600 dark:text-emerald-400'
                  : 'bg-gray-50 dark:bg-gray-800 border-gray-200 dark:border-gray-700 text-gray-700 dark:text-gray-300 hover:border-gray-300 dark:hover:border-gray-600'
                }`}
            >
              {copied ? <CheckCheck size={15} /> : <Copy size={15} />}
              {copied ? 'Copied!' : 'Copy Text'}
            </button>

            {/* Email */}
            <button
              id="whatsapp-email-btn"
              onClick={handleEmail}
              className="flex items-center justify-center gap-2 py-2.5 px-4 rounded-xl
                border border-gray-200 dark:border-gray-700
                bg-gray-50 dark:bg-gray-800
                text-gray-700 dark:text-gray-300
                hover:border-blue-500/40 hover:text-blue-600 dark:hover:text-blue-400
                text-sm font-semibold
                hover:scale-[1.02] active:scale-[0.98] transition-all duration-200"
            >
              <Mail size={15} />
              Email
            </button>
          </div>

          {/* Footer note */}
          <p className="flex items-center justify-center gap-1.5 text-[10px] text-gray-400 dark:text-gray-500 text-center pt-1">
            <Sparkles size={10} />
            Generated by LegalEase AI · Data stays on your device
          </p>
        </div>
      </div>
    </div>,
    document.body
  );
}
